story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('', include('story9.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('activity', views.list_activity, name='list_activity'),
    path('activity/add', views.add, name='add'),
    path('delete/<int:index>', views.delete_activity, name='delete_activity'),
    path('delete/participant/<int:index>', views.delete_participant, name='delete_participant'),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    activity = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    def __str__(self):
        return self.activity
    
class Participant(models.Model):
    name = models.CharField(max_length=100)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name

story6/forms.py
from django import forms
from .models import Activity, Participant

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity':forms.TextInput(attrs={
                'class':'form-control',
            }),
            'category':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Example: Arts, Sports',
            })
        }


class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={
                'class':'form-control',
            })
        }

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Activity, Participant
from .forms import ActivityForm, ParticipantForm
from story6 import forms, models

# Create your views here.
def list_activity(request):
    activity = Activity.objects.all()
    participant = Participant.objects.all()
    form_activity = ActivityForm(request.POST)
    form_participant = ParticipantForm(request.POST)
    context = {
        'activity':activity,
        'participant':participant,
        'form_activity':form_activity,
        'form_participant':form_participant,
    }

    return render(request, 'list_activity.html', context)

def add(request):
    activity = Activity.objects.all()
    participant = Participant.objects.all()
    form_activity = ActivityForm(request.POST)
    form_participant = ParticipantForm(request.POST)
    context = {
        'activity':activity,
        'participant':participant,
        'form_activity':form_activity,
        'form_participant':form_participant,
    }

    if request.method == "POST":
        if form_activity.is_valid():
            form_activity.save()
            return redirect('/story6/activity')
        elif form_participant.is_valid():
            form_participant.save()
            return redirect('/story6/activity')
    return render(request, 'add_activity.html', context)


def delete_activity(request, index):
    activity = Activity.objects.get(id=index)
    activity.delete()
    return redirect('/story6/activity')


def delete_participant(request, index):
    participant = Participant.objects.get(id=index)
    participant.delete()
    return redirect('/story6/activity')

story6/templates/add_activity.html
{% extends "base.html" %}
{% block meta %}
{% endblock meta %}
{% block content %}
{% load static %}
<body style="background-color: #FCDAD8;">
    <!-- Header-->
    <header>

        <!-- Slideshow text -->
        <h1>Activity</h1>
        <p align="center" class="typewrite" data-period="2000" data-type='[ "Hello!!!", "lagi ada kegiatan apa nih?", "lagi sibuk?", "jadwal berantakan?", "catat jadwal di bawah yuk!"]'>
            <span class="wrap"></span>
        </p>
        
    </header>

    <div class="container">
        <hr>
        <h1 class="row justify-content-md-center">Add Activity</h1>
        <div class="row justify-content-md-center">
            <form class="form-group" method="POST">
                {% csrf_token %}
                {% for field in form_activity %}
                <h3 class="w-100 justify-content-center my-1">{{ field.label }}</h3>
                <h3 class="w-100 justify-content-center my-1">{{ field }}</h3>
                {% endfor %}
                <br><br>
                <input type="submit" value="Submit" class="btn btn-outline-dark btn-lg">    
            </form>
        </div>
        <br><br><br><br>
        <h1 class="row justify-content-md-center">Join the Activity</h1>
        <div class="row justify-content-md-center">
            <form class="form-group" method="POST">
                {% csrf_token %}
                {% for person in form_participant %}
                <h3 class="w-100 justify-content-center my-1">{{ person.label }}</h3>
                <h3 class="w-100 justify-content-center my-1">{{ person }}</h3>
               
                {% endfor %}
                <br><br>
                <input name="participant" type="text" value="{{ participant.id }}" style="display: none;">
                <button type="submit" class="btn btn-outline-dark btn-lg">Join</button>
            </form>
        </div>

        <br><br><br><br>
        <div class="row">
            <div class="col">
                <a type="button" class="btn btn-danger btn-lg btn-block" href="{% url 'story6:list_activity' %}">Back</a>
            </div>
        </div>
    
    </div>
</body>
{% endblock content %}

story6/templates/list_activity.html
{% extends "base.html" %}
{% block meta %}
{% endblock meta %}
{% block content %}
{% load static %}
<body style="background-color: #FCDAD8;">
    <!-- Header-->
    <header>

        <!-- Slideshow text -->
        <h1>Activity</h1>
        <p align="center" class="typewrite" data-period="2000" data-type='[ "Hello!!!", "lagi ada kegiatan apa nih?", "lagi sibuk?", "jadwal berantakan?", "catat jadwal di bawah yuk!"]'>
            <span class="wrap"></span>
        </p>
        
    </header>

    <div class="container">
        <hr>
        <div class="row">
            <div class="col">
                <a type="button" class="btn btn-danger btn-lg btn-block" href="{% url 'story6:add' %}">Add and Join Activity</a>
            </div>
        </div>
        <div class="d-flex justify-content-around flex-wrap pb-4">
            {% for x in activity %}
            <div class="card bg-danger text-white mt-5" style="width: 18rem;">
                <div class="card-header">
                    <div class="row">
                        <h5 class="col-10 mb-2"><strong>Activity</strong> <br> {{ x.activity }}</h5>
                        <h5 class="col-10 mb-2"><strong>Category</strong> <br> {{ x.category }}</h5>
                        <a href="{% url 'story6:delete_activity' x.id %}" class="col-2">
                            <button type="button" class="close mb-2">&times;</button>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <h6 class="card-title">Participants</h6>
                    <p></p>
                    <ul>
    
                        {% for y in participant %}
                            {% if y.activity == x %}
                            <li class="row">
                                <h5 class="col-10">{{ y.name }}</h5>
                                <a href="delete/participant/{{ y.id }}" class="col-2">
                                    <button type="button" class="close">&times;</button>
                                </a>    
                            </li>
                            {% endif %}
                        {% endfor %}
    
                    </ul>
                </div>
            </div>
            {% endfor %}

            
    
    </div>
</body>
{% endblock content %}