homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('memories', views.memories, name='memories'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('', include('story9.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1'),
]

story1/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1.html')

story1/templates/story1.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	<meta charset="utf-8" />
	<title>Afna | Website</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<!--Custom fonts. To improve load times, remove this and update the h1 styling in style.css--> 
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
	<!-- stylesheets -->
	<link rel="stylesheet" href="{% static '../static/story1/css/style.css' %}">
	<link rel="stylesheet" href="{% static '../static/story1/css/navbar.css' %}">
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static '../static/story1/images/logo-icon.png' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
	
	<!-- Header-->
	<header>
		<div class="topnav" id="myTopnav">
			<a class="active" href="{% url 'homepage:index' %}">Home</a>
            <a href="{% url 'homepage:index' %}#education">Education</a>
			<a href="{% url 'homepage:index' %}#experience">Experience</a>
			<a href="{% url 'homepage:index' %}#contact">Contact</a>
			<a href="javascript:void(0);" class="icon" onclick="myFunction()">
				<i class="fa fa-bars"></i>
			</a>
        </div>

		<!-- Slideshow text -->
		<h1>Afnadiati Hartatika</h1>
		<p align="center" class="typewrite" data-period="2000" data-type='[ "Hello...", "Welcome to my website", "Information Systems student", "1906398931", "Class of 2019"]'>
			<span class="wrap"></span>
		</p>
		
	</header>
	
	<div class="container" id="about">
		
		<!-- Introduction-->
		<section class="center">
			<h1>About me</h1>
			<p>
				I am Afnadiati Hartatika a second year Information Systems student, Faculty of Computer Science, University of Indonesia. 
				Originally from Indonesia, based in Jakarta. 
			</p>
		</section>
	</div>

	<!-- Spotlight -->
	<section class="spotlight">
		<div class="container">
			<div class="row">
				<div class="grid-3">
					<img style="vertical-align:middle;margin:0px 50px" src="{% static '/story1/images/afna.jpg' %}">
				</div>
				<div class="grid-3">
					<div class="center">
						<h1 style="font-size:1.6em">Interested in business, management, design and programming. Now, I often spend my free time to exploring it.
							I don't have a specific hobby, but I usually spend my spare time to design anything and try something new. 
						</h1>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="container" id="education">	
		<!-- Testimonials-->	
		<section class="education">
			<div class="row">
				<h1 class="center">Education</h1>
				<div class="grid-2">
					<img src="https://blog-media.lifepal.co.id/wp-content/uploads/2019/08/19132449/Universitas-Indonesia-Jadi-Dambaan-Pelajar-SMA-Shutterstock.-900x639.jpg">
					<h3><strong>University of Indonesia</strong></h3>
					<p>Information Systems <br> Faculty of Computer Science <br> 2019 - present</p>
				</div>
				
				<div class="grid-2">
					<img src="https://sman104-jkt.sch.id/wp-content/uploads/2018/10/sman104-sekolah1-390x220.jpeg">
					<h3><strong>SMAN 104 Jakarta</strong></h3>
					<p>2016 - 2019</p>
				</div>
		
				<div class="grid-2">
					<img src="https://dwikisetiyawan.files.wordpress.com/2013/01/tampak_depan_smp_negeri_103_jakarta.jpg">
					<h3><strong>SMPN 103 Jakarta</strong></h2>
					<p>2013 - 2016</p>
				</div>
			</div>
		</section>
	</div> <!-- End container-->
	

	<!-- New container-->
	<div class="container" id="experience">
		<hr>
		<section class="table-block">	
			<h2>Organizational Experience</h2>
		</section>
			
		<!--Organizational Experience Tables-->
		<section class="experience">
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2017 - 2018</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>Women's (Akhwat) Coordinator</strong></h3>
						<h3>Rohis SMAN 104 Jakarta</h3>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2016 - 2017</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>Staff of Regeneration Division</strong></h3>
						<h3>Rohis SMAN 104 Jakarta</h3>
					</ul>
				</div>
			</div>
		</section>
		
		
		<hr>

		<!--Commitee Experience Tables-->
		<section class="table-block">	
			<h2>Committee Experience</h2>
		</section>
			
		<!--Experience Tables-->
		<section class="experience">
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2020</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>Vice Project Officer SIWAK-NG</strong></h3>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2020</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>Staff of Academic PMB Fasilkom UI</strong></h3>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2018</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>PIC of Design HIASTON (Hizqova Art & Solidarity Competition)</strong></h3>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="grid-2">
					<h3 align="center"><strong>2018</strong></h3>
				</div>
				<div class="grid-4">
					<ul>
						<h3><strong>Secretary of PLUG 4 (Pengobatan Massal Umum Gratis)</strong></h3>
					</ul>
				</div>
			</div>
		</section>
		
		<hr>

		<!-- Contact me -->
		<section class="table-block" id="contact">	
			<h2>Contact me</h2>
		</section>

		<section>
			<!--List of social media-->
			<div class="center">
				<div class="grid-2">
					<a href="mailto:afnadiatihartatika@gmail.com" target="_blank"><img width="40px" src="{% static 'story1/images/gmail.svg' %}"></a>
				</div>
				<div class="grid-2">
					<a href="https://www.instagram.com/afnahartatika" target="_blank"><img width="40px" src="{% static '/story1/images/instagram.svg' %}"></a>
				</div>
				<div class="grid-2">
					<a href="https://www.linkedin.com/in/afnadiati-hartatika-18265b88" target="_blank"><img width="40px" src="{% static '/story1/images/linkedin.svg' %}"></a>
				</div>
			</div>
		</section>
		
		
		<script>
			/* Responsive Navbar */
			function myFunction() {
				var x = document.getElementById("myTopnav");
				if (x.className === "topnav") {
					x.className += " responsive";
				} else {
					x.className = "topnav";
				}
			}


			/* Slideshow Text */
			var TxtType = function(el, toRotate, period) {
				this.toRotate = toRotate;
				this.el = el;
				this.loopNum = 0;
				this.period = parseInt(period, 10) || 2000;
				this.txt = '';
				this.tick();
				this.isDeleting = false;
			};

			TxtType.prototype.tick = function() {
				var i = this.loopNum % this.toRotate.length;
				var fullTxt = this.toRotate[i];

				if (this.isDeleting) {
				this.txt = fullTxt.substring(0, this.txt.length - 1);
				} else {
				this.txt = fullTxt.substring(0, this.txt.length + 1);
				}

				this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

				var that = this;
				var delta = 200 - Math.random() * 100;

				if (this.isDeleting) { delta /= 2; }

				if (!this.isDeleting && this.txt === fullTxt) {
				delta = this.period;
				this.isDeleting = true;
				} else if (this.isDeleting && this.txt === '') {
				this.isDeleting = false;
				this.loopNum++;
				delta = 500;
				}

				setTimeout(function() {
				that.tick();
				}, delta);
			};

			window.onload = function() {
				var elements = document.getElementsByClassName('typewrite');
				for (var i=0; i<elements.length; i++) {
					var toRotate = elements[i].getAttribute('data-type');
					var period = elements[i].getAttribute('data-period');
					if (toRotate) {
					new TxtType(elements[i], JSON.parse(toRotate), period);
					}
				}
				// INJECT CSS
				var css = document.createElement("style");
				css.type = "text/css";
				css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
				document.body.appendChild(css);
			};
		</script>
			

		<!-- Footer -->
		<footer class="center">
			<hr>
			<span>build with 🧡 by</span> <br>
			<span>&copy; Afnadiati Hartatika 2020</span>
		</footer>
		
	</div><!-- End Container -->
	
</body>
</html>