story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('', include('story9.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('form', views.schedule, name='schedule'),
    path('list', views.list_course, name='list_course'),
    path('details/<int:index>', views.details_course, name='details_course'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('activity', views.list_activity, name='list_activity'),
    path('activity/add', views.add, name='add'),
    path('delete/<int:index>', views.delete_activity, name='delete_activity'),
    path('delete/participant/<int:index>', views.delete_participant, name='delete_participant'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='story7'),
]

templates/base.html
{% block content %}
{% endblock content %}
<!DOCTYPE html>
<html lang="en">
	{% load static %}

<head>
	{% block meta %}
	{% endblock meta %}
	<meta charset="utf-8" />
	<title>Afna | Website</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	
	<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!--Custom fonts. To improve load times, remove this and update the h1 styling in style.css--> 
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
	<!-- JavaScript -->
	<script src="{% static 'js/story.js' %}" type="text/javascript"></script>
	<script src='https://kit.fontawesome.com/a076d05399.js'></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>
	<!-- stylesheets -->
	<link rel="stylesheet" href="{% static '/homepage/css/style.css' %}">
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static '/homepage/images/logo-new.png' %}" type="image/png">
</head>

<body>
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:#EB3437;">
			<a class="navbar-brand" href="{% url 'homepage:index' %}#about">afna</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		  
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'homepage:index' %}">Home </a>
				</li>
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'homepage:index' %}#education">Education</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'homepage:index' %}#experience">Experience</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'homepage:index' %}#contact">Contact</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  More
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						{% if user.is_authenticated == True %}
							<h6><a class="dropdown-item" href="/login">My Profile <br> @{{ user.username }}</a></h6>
							<div class="dropdown-divider"></div>
						{% endif %}
						<h6><a class="dropdown-item" href="{% url 'story1:story1' %}">Story 1</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 5</h6>
						<h6><a class="dropdown-item" href="{% url 'story5:list_course' %}">Schedule</a></h6>
						<h6><a class="dropdown-item" href="{% url 'story5:schedule' %}">Add Schedule</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 6</h6>
						<h6><a class="dropdown-item" href="{% url 'story6:list_activity' %}">Activity</a></h6>
						<h6><a class="dropdown-item" href="{% url 'story6:add' %}">Add Activity</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 7</h6>
						<h6><a class="dropdown-item" href="{% url 'story7:story7' %}">About Me</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 8</h6>
						<h6><a class="dropdown-item" href="{% url 'story8:books' %}">Books</a></h6>
						<div class="dropdown-divider"></div>
						<h6><a class="dropdown-item" href="{% url 'homepage:memories' %}">Memories</a></h6>
					</div>

				  </li>
				  <li>
					{% if user.is_authenticated == False %}
						<a class="nav-link active" type="submit" href="/login">Sign in</a>
						
					{% else %}
						<a class="nav-link active" type="submit" href="/logout">Sign out</a>
					{% endif %}
				  </li>
			  </ul>
            </div>
        </nav>

        

        <!-- Contact me -->
        <div class="container">
            <hr>

            <h1 id="contact">Contact me</h1>

            <section class="container px-lg-5">
                <br><br><br>
                <!--List of social media-->
                <div class="row mx-lg-n5">
                        <div class="col py-3 px-lg-5 center">
                            <a href="mailto:afnadiatihartatika@gmail.com" target="_blank"><img width="70px" src="{% static '/homepage/images/gmail.svg' %}"></a>
                        </div>
                        <div class="col py-3 px-lg-5 center">
                            <a href="https://www.instagram.com/afnahartatika" target="_blank"><img width="70px" src="{% static '/homepage/images/instagram.svg' %}"></a>
                        </div>
                        <div class="col py-3 px-lg-5 center">
                            <a href="https://www.linkedin.com/in/afnadiati-hartatika-18265b88" target="_blank"><img width="70px" src="{% static '/homepage/images/linkedin.svg' %}"></a>
                        </div>
                </div>
            </section>
        </div>
		
	
		<!-- Footer -->
		<footer class="center">
			<hr>
			<span>build with 🧡 by</span> <br>
			<span>&copy; 2020 Afna</span>
		</footer>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

		<script>
			/* Slideshow Text */
			var TxtType = function(el, toRotate, period) {
				this.toRotate = toRotate;
				this.el = el;
				this.loopNum = 0;
				this.period = parseInt(period, 10) || 2000;
				this.txt = '';
				this.tick();
				this.isDeleting = false;
			};

			TxtType.prototype.tick = function() {
				var i = this.loopNum % this.toRotate.length;
				var fullTxt = this.toRotate[i];

				if (this.isDeleting) {
				this.txt = fullTxt.substring(0, this.txt.length - 1);
				} else {
				this.txt = fullTxt.substring(0, this.txt.length + 1);
				}

				this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

				var that = this;
				var delta = 200 - Math.random() * 100;

				if (this.isDeleting) { delta /= 2; }

				if (!this.isDeleting && this.txt === fullTxt) {
				delta = this.period;
				this.isDeleting = true;
				} else if (this.isDeleting && this.txt === '') {
				this.isDeleting = false;
				this.loopNum++;
				delta = 500;
				}

				setTimeout(function() {
				that.tick();
				}, delta);
			};

			window.onload = function() {
				var elements = document.getElementsByClassName('typewrite');
				for (var i=0; i<elements.length; i++) {
					var toRotate = elements[i].getAttribute('data-type');
					var period = elements[i].getAttribute('data-period');
					if (toRotate) {
					new TxtType(elements[i], JSON.parse(toRotate), period);
					}
				}
				// INJECT CSS
				var css = document.createElement("style");
				css.type = "text/css";
				css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
				document.body.appendChild(css);
			};
		</script>
</body>   
</html> 

templates/navbar_footer.html
{% block content %}
{% endblock content %}
<!DOCTYPE html>
<html lang="en">
	{% load static %}

<head>
	{% block meta %}
	{% endblock meta %}
	<meta charset="utf-8" />
	<title>Afna | Website</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	
	<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!--Custom fonts. To improve load times, remove this and update the h1 styling in style.css--> 
	<link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
	<!-- stylesheets -->
	<link rel="stylesheet" href="{% static '/homepage/css/style.css' %}">
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static '/homepage/images/logo-new.png' %}" type="image/png">
</head>

<body>
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:#EB3437;">
			<a class="navbar-brand" href="{% url 'homepage:index' %}#about">afna</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		  
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'homepage:index' %}">Home </a>
				</li>
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'homepage:index' %}#education">Education</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'homepage:index' %}#experience">Experience</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'homepage:index' %}#contact">Contact</a>
                </li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  More
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<h6><a class="dropdown-item" href="{% url 'story1:story1' %}">Story 1</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 5</h6>
						<h6><a class="dropdown-item" href="{% url 'story5:list_course' %}">Schedule</a></h6>
						<h6><a class="dropdown-item" href="{% url 'story5:schedule' %}">Add Schedule</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 6</h6>
						<h6><a class="dropdown-item" href="{% url 'story6:list_activity' %}">Activity</a></h6>
						<h6><a class="dropdown-item" href="{% url 'story6:add' %}">Add Activity</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 7</h6>
						<h6><a class="dropdown-item" href="{% url 'story7:story7' %}">About Me</a></h6>
						<div class="dropdown-divider"></div>
						<h6 class="dropdown-item">Story 8</h6>
						<h6><a class="dropdown-item" href="{% url 'story8:books' %}">Books</a></h6>
						<div class="dropdown-divider"></div>
						<h6><a class="dropdown-item" href="{% url 'homepage:memories' %}">Memories</a></h6>
					</div>
				  </li>
				  <li>
					{% if user.is_authenticated == False %}
						<a class="nav-link active" type="submit" href="/login">Sign in</a>
						
					{% else %}
						<a class="nav-link active" type="submit" href="/logout">Sign out</a>
					{% endif %}
				  </li>
			  </ul>
            </div>
        </nav>

        

        <!-- Contact me -->
        <div class="container">
            <hr>

            <h1 id="contact">Contact me</h1>

            <section class="container px-lg-5">
                <br><br><br>
                <!--List of social media-->
                <div class="row mx-lg-n5">
                        <div class="col py-3 px-lg-5 center">
                            <a href="mailto:afnadiatihartatika@gmail.com" target="_blank"><img width="70px" src="{% static '/homepage/images/gmail.svg' %}"></a>
                        </div>
                        <div class="col py-3 px-lg-5 center">
                            <a href="https://www.instagram.com/afnahartatika" target="_blank"><img width="70px" src="{% static '/homepage/images/instagram.svg' %}"></a>
                        </div>
                        <div class="col py-3 px-lg-5 center">
                            <a href="https://www.linkedin.com/in/afnadiati-hartatika-18265b88" target="_blank"><img width="70px" src="{% static '/homepage/images/linkedin.svg' %}"></a>
                        </div>
                </div>
            </section>
        </div>
		
	
		<!-- Footer -->
		<footer class="center">
			<hr>
			<span>build with 🧡 by</span> <br>
			<span>&copy; 2020 Afna</span>
        </footer>
        
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        
</body>   
</html> 